# Generated by Django 4.1 on 2022-11-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StaffLogin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffdata",
            name="staffHash",
            field=models.CharField(default="None", max_length=250, null=True),
        ),
    ]
